# This lines are automatically generated by tool/opcode_for_pp.pl.
# ANY CHANGES WILL BE LOST!
package Text::Xslate::PP::Const;

package Text::Xslate::PP;

use strict;

use constant TXARGf_SV      => 0x01;
use constant TXARGf_INT     => 0x02;
use constant TXARGf_KEY     => 0x04;
use constant TXARGf_VAR     => 0x08;
use constant TXARGf_GOTO    => 0x10;

use constant TXCODE_W_SV    => TXARGf_SV;
use constant TXCODE_W_INT   => (TXARGf_SV | TXARGf_INT);
use constant TXCODE_W_VAR   => (TXARGf_SV | TXARGf_INT | TXARGf_VAR);
use constant TXCODE_W_KEY   => (TXARGf_SV | TXARGf_KEY);
use constant TXCODE_GOTO    => (TXARGf_SV | TXARGf_INT | TXARGf_GOTO);

# template representation, stored in $self->{template}{$file}
use constant TXo_NAME           => 0;
use constant TXo_ERROR_HANDLER  => 1;
use constant TXo_MTIME          => 2;
use constant TXo_CACHEPATH      => 3;
use constant TXo_FULLPATH       => 4;

# vm execution frame
use constant TXframe_NAME       => 0;
use constant TXframe_OUTPUT     => 1;
use constant TXframe_RETADDR    => 2;
use constant TXframe_START_LVAR => 3;

use constant TX_VERBOSE_DEFAULT => 1;


our %OPS = (
    noop             => 0,
    move_to_sb       => 1,
    move_from_sb     => 2,
    save_to_lvar     => 3,
    load_lvar        => 4,
    load_lvar_to_sb  => 5,
    localize_s       => 6,
    push             => 7,
    pushmark         => 8,
    nil              => 9,
    literal          => 10,
    literal_i        => 11,
    fetch_s          => 12,
    fetch_field      => 13,
    fetch_field_s    => 14,
    print            => 15,
    print_raw        => 16,
    print_raw_s      => 17,
    include          => 18,
    for_start        => 19,
    for_iter         => 20,
    add              => 21,
    sub              => 22,
    mul              => 23,
    div              => 24,
    mod              => 25,
    concat           => 26,
    and              => 27,
    dand             => 28,
    or               => 29,
    dor              => 30,
    not              => 31,
    minus            => 32,
    max_index        => 33,
    builtin_mark_raw => 34,
    builtin_unmark_raw => 35,
    builtin_html_escape => 36,
    eq               => 37,
    ne               => 38,
    lt               => 39,
    le               => 40,
    gt               => 41,
    ge               => 42,
    ncmp             => 43,
    scmp             => 44,
    symbol           => 45,
    macro_end        => 46,
    funcall          => 47,
    methodcall_s     => 48,
    make_array       => 49,
    make_hash        => 50,
    enter            => 51,
    leave            => 52,
    goto             => 53,
    depend           => 54,
    macro_begin      => 55,
    macro_nargs      => 56,
    macro_outer      => 57,
    end              => 58,
); # %OPS

our @OPCODE = (
    \&Text::Xslate::PP::Opcode::op_noop,                # 0
    \&Text::Xslate::PP::Opcode::op_move_to_sb,          # 1
    \&Text::Xslate::PP::Opcode::op_move_from_sb,        # 2
    \&Text::Xslate::PP::Opcode::op_save_to_lvar,        # 3
    \&Text::Xslate::PP::Opcode::op_load_lvar,           # 4
    \&Text::Xslate::PP::Opcode::op_load_lvar_to_sb,     # 5
    \&Text::Xslate::PP::Opcode::op_localize_s,          # 6
    \&Text::Xslate::PP::Opcode::op_push,                # 7
    \&Text::Xslate::PP::Opcode::op_pushmark,            # 8
    \&Text::Xslate::PP::Opcode::op_nil,                 # 9
    \&Text::Xslate::PP::Opcode::op_literal,             # 10
    \&Text::Xslate::PP::Opcode::op_literal_i,           # 11
    \&Text::Xslate::PP::Opcode::op_fetch_s,             # 12
    \&Text::Xslate::PP::Opcode::op_fetch_field,         # 13
    \&Text::Xslate::PP::Opcode::op_fetch_field_s,       # 14
    \&Text::Xslate::PP::Opcode::op_print,               # 15
    \&Text::Xslate::PP::Opcode::op_print_raw,           # 16
    \&Text::Xslate::PP::Opcode::op_print_raw_s,         # 17
    \&Text::Xslate::PP::Opcode::op_include,             # 18
    \&Text::Xslate::PP::Opcode::op_for_start,           # 19
    \&Text::Xslate::PP::Opcode::op_for_iter,            # 20
    \&Text::Xslate::PP::Opcode::op_add,                 # 21
    \&Text::Xslate::PP::Opcode::op_sub,                 # 22
    \&Text::Xslate::PP::Opcode::op_mul,                 # 23
    \&Text::Xslate::PP::Opcode::op_div,                 # 24
    \&Text::Xslate::PP::Opcode::op_mod,                 # 25
    \&Text::Xslate::PP::Opcode::op_concat,              # 26
    \&Text::Xslate::PP::Opcode::op_and,                 # 27
    \&Text::Xslate::PP::Opcode::op_dand,                # 28
    \&Text::Xslate::PP::Opcode::op_or,                  # 29
    \&Text::Xslate::PP::Opcode::op_dor,                 # 30
    \&Text::Xslate::PP::Opcode::op_not,                 # 31
    \&Text::Xslate::PP::Opcode::op_minus,               # 32
    \&Text::Xslate::PP::Opcode::op_max_index,           # 33
    \&Text::Xslate::PP::Opcode::op_builtin_mark_raw,    # 34
    \&Text::Xslate::PP::Opcode::op_builtin_unmark_raw,  # 35
    \&Text::Xslate::PP::Opcode::op_builtin_html_escape, # 36
    \&Text::Xslate::PP::Opcode::op_eq,                  # 37
    \&Text::Xslate::PP::Opcode::op_ne,                  # 38
    \&Text::Xslate::PP::Opcode::op_lt,                  # 39
    \&Text::Xslate::PP::Opcode::op_le,                  # 40
    \&Text::Xslate::PP::Opcode::op_gt,                  # 41
    \&Text::Xslate::PP::Opcode::op_ge,                  # 42
    \&Text::Xslate::PP::Opcode::op_ncmp,                # 43
    \&Text::Xslate::PP::Opcode::op_scmp,                # 44
    \&Text::Xslate::PP::Opcode::op_symbol,              # 45
    \&Text::Xslate::PP::Opcode::op_macro_end,           # 46
    \&Text::Xslate::PP::Opcode::op_funcall,             # 47
    \&Text::Xslate::PP::Opcode::op_methodcall_s,        # 48
    \&Text::Xslate::PP::Opcode::op_make_array,          # 49
    \&Text::Xslate::PP::Opcode::op_make_hash,           # 50
    \&Text::Xslate::PP::Opcode::op_enter,               # 51
    \&Text::Xslate::PP::Opcode::op_leave,               # 52
    \&Text::Xslate::PP::Opcode::op_goto,                # 53
    \&Text::Xslate::PP::Opcode::op_depend,              # 54
    \&Text::Xslate::PP::Opcode::op_macro_begin,         # 55
    \&Text::Xslate::PP::Opcode::op_macro_nargs,         # 56
    \&Text::Xslate::PP::Opcode::op_macro_outer,         # 57
    \&Text::Xslate::PP::Opcode::op_end,                 # 58
); # @OPCODE

our @OPARGS = (
    0,             # noop
    0,             # move_to_sb
    0,             # move_from_sb
    TXCODE_W_VAR,  # save_to_lvar
    TXCODE_W_VAR,  # load_lvar
    TXCODE_W_VAR,  # load_lvar_to_sb
    TXCODE_W_KEY,  # localize_s
    0,             # push
    0,             # pushmark
    0,             # nil
    TXCODE_W_SV,   # literal
    TXCODE_W_INT,  # literal_i
    TXCODE_W_KEY,  # fetch_s
    0,             # fetch_field
    TXCODE_W_KEY,  # fetch_field_s
    0,             # print
    0,             # print_raw
    TXCODE_W_SV,   # print_raw_s
    0,             # include
    TXCODE_W_VAR,  # for_start
    TXCODE_GOTO,   # for_iter
    0,             # add
    0,             # sub
    0,             # mul
    0,             # div
    0,             # mod
    TXCODE_W_SV,   # concat
    TXCODE_GOTO,   # and
    TXCODE_GOTO,   # dand
    TXCODE_GOTO,   # or
    TXCODE_GOTO,   # dor
    0,             # not
    0,             # minus
    0,             # max_index
    0,             # builtin_mark_raw
    0,             # builtin_unmark_raw
    0,             # builtin_html_escape
    0,             # eq
    0,             # ne
    0,             # lt
    0,             # le
    0,             # gt
    0,             # ge
    0,             # ncmp
    0,             # scmp
    TXCODE_W_KEY,  # symbol
    TXCODE_W_INT,  # macro_end
    0,             # funcall
    TXCODE_W_KEY,  # methodcall_s
    0,             # make_array
    0,             # make_hash
    0,             # enter
    0,             # leave
    TXCODE_GOTO,   # goto
    TXCODE_W_SV,   # depend
    TXCODE_W_KEY,  # macro_begin
    TXCODE_W_INT,  # macro_nargs
    TXCODE_W_INT,  # macro_outer
    0,             # end
); # @OPARGS

1;
__END__

=pod

=head1 NAME

Text::Xslate::PP::Const - Text::Xslate constants in pure Perl

=head1 DESCRIPTION

This module is used by Text::Xslate::PP internally.

=head1 SEE ALSO

L<Text::Xslate>

L<Text::Xslate::PP>

=head1 LICENSE AND COPYRIGHT

Copyright (c) 2010 by Makamaka Hannyaharamitu (makamaka).

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

