---
abstract: 'High performance template engine'
author:
  - 'Fuji, Goro (gfx) <gfuji(at)cpan.org>'
build_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.42
  ExtUtils::ParseXS: 2.21
  Test::More: 0.88
  Test::Requires: 0
configure_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.97'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Text::Xslate
name: Text-Xslate
no_index:
  directory:
    - example
    - inc
    - t
    - xt
requires:
  Any::Moose: 0.13
  Mouse: 0.55
  MouseX::Getopt: 0.2601
  MouseX::NativeTraits: 0.002
  XSLoader: 0.1
  parent: 0.221
  perl: 5.10.0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/gfx/p5-Text-Xslate.git
version: 0.1018
