---
abstract: 'Scalable template engine for Perl5'
author:
  - 'Fuji, Goro (gfx) <gfuji(at)cpan.org>'
build_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.42
  ExtUtils::ParseXS: 2.21
  Test::More: 0.88
  Test::Requires: 0
configure_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Text::Xslate
name: Text-Xslate
no_index:
  directory:
    - example
    - inc
    - t
    - xt
requires:
  Any::Moose: 0.13
  Data::MessagePack: 0.30
  Mouse: 0.61
  MouseX::Getopt: 0.2601
  Scalar::Util: 1.14
  XSLoader: 0.1
  parent: 0.221
  perl: 5.8.1
resources:
  homepage: http://xslate.org/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/gfx/p5-Text-Xslate.git
version: 1.1001
